### ISSUE TITLE
Linux .clap format support

### ISSUE THREAD

**Issue by ghost** [astriiddev/Ami-Sampler-VST#11]
Hi,
I would like to know if there is a possibility to have this beautiful sampler in clap format, 

Thank you

**Comment by astriiddev** [comment]
Ami Sampler is built within the JUCE framework. Currently, CLAP isn't supported on JUCE, but there is an experimental extension for clap support.
I don't have a plug-in host that can load CLAP plugins, so I have no way to test if a CLAP version of Ami would be stable. 
The CLAP extension for JUCE is open source, so feel free to attempt building Ami into a CLAP plug-in if you'd like 🙂

**Comment by ghost** [comment]
anyway, thank you..... cheers
